import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

const cliPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist', 'cli.js');

function cli(...args) {
  return spawnSync(process.execPath, [cliPath, ...args], { encoding: 'utf8', windowsHide: true });
}

async function workspace() {
  return mkdtemp(path.join(tmpdir(), 'agents-crew-plugin-'));
}

test('plugin list reports supported hosts', () => {
  const result = cli('plugin', 'list', '--json');
  assert.equal(result.status, 0, result.stderr);
  const hosts = JSON.parse(result.stdout).plugins.map((plugin) => plugin.host);
  assert.deepEqual(hosts, ['antigravity', 'codex', 'claude-code', 'opencode', 'github-copilot']);
});

test('plugin install dry-run reports files without writing', async () => {
  const root = await workspace();
  const result = cli('plugin', 'install', 'antigravity', '--workspace', root, '--dry-run', '--json');
  assert.equal(result.status, 0, result.stderr);
  const output = JSON.parse(result.stdout);
  assert.equal(output.installed[0].host, 'antigravity');
  assert.equal(output.installed[0].dryRun, true);
  assert.equal(output.installed[0].files.length, 3);
  assert.equal(existsSync(path.join(root, '.agents', 'hooks', 'manifest.json')), false);
});

test('plugin install writes manifest and command docs', async () => {
  const root = await workspace();
  const result = cli('plugin', 'install', 'codex', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const manifestPath = path.join(root, '.codex', 'agents-crew', 'manifest.json');
  const commandsPath = path.join(root, '.codex', 'agents-crew', 'COMMANDS.md');
  assert.equal(existsSync(manifestPath), true);
  assert.equal(existsSync(commandsPath), true);
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  assert.equal(manifest.host, 'codex');
  assert.match(await readFile(commandsPath, 'utf8'), /generated by agents-crew plugin installer/);
});

test('plugin install all writes hook integration files for each host', async () => {
  const root = await workspace();
  const result = cli('plugin', 'install', 'all', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const output = JSON.parse(result.stdout);
  assert.equal(output.installed.length, 5);
  assert.equal(existsSync(path.join(root, '.agents', 'hooks.json')), true);
  assert.equal(existsSync(path.join(root, '.codex', 'hooks.json')), true);
  assert.equal(existsSync(path.join(root, '.claude', 'plugins', 'agents-crew', 'hooks', 'hooks.json')), true);
  assert.equal(existsSync(path.join(root, '.opencode', 'plugins', 'agents-crew.js')), true);
  assert.equal(existsSync(path.join(root, '.github', 'hooks', 'agents-crew.json')), true);
});

test('plugin install skips existing files unless forced', async () => {
  const root = await workspace();
  assert.equal(cli('plugin', 'install', 'opencode', '--workspace', root, '--json').status, 0);
  const result = cli('plugin', 'install', 'opencode', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const actions = JSON.parse(result.stdout).installed[0].files.map((file) => file.action);
  assert.deepEqual(actions, ['skip', 'skip', 'skip']);
});

test('plugin install --force overwrites existing generated files', async () => {
  const root = await workspace();
  assert.equal(cli('plugin', 'install', 'codex', '--workspace', root, '--json').status, 0);
  const manifestPath = path.join(root, '.codex', 'agents-crew', 'manifest.json');
  await writeFile(manifestPath, 'custom');
  const result = cli('plugin', 'install', 'codex', '--workspace', root, '--force', '--json');
  assert.equal(result.status, 0, result.stderr);
  const actions = JSON.parse(result.stdout).installed[0].files.map((file) => file.action);
  assert.equal(actions[0], 'overwrite');
  assert.match(await readFile(manifestPath, 'utf8'), /generated by agents-crew plugin installer/);
});

test('plugin uninstall removes only generated files', async () => {
  const root = await workspace();
  assert.equal(cli('plugin', 'install', 'claude-code', '--workspace', root, '--json').status, 0);
  const manifestPath = path.join(root, '.claude', 'commands', 'agents-crew', 'manifest.json');
  const result = cli('plugin', 'uninstall', 'claude-code', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const actions = JSON.parse(result.stdout).uninstalled[0].files.map((file) => file.action);
  assert.deepEqual(actions, ['remove', 'remove', 'remove', 'remove']);
  assert.equal(existsSync(manifestPath), false);
});

test('plugin uninstall skips user-managed files without generated marker', async () => {
  const root = await workspace();
  const filePath = path.join(root, '.codex', 'agents-crew', 'manifest.json');
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, '{"custom":true}\n');
  const result = cli('plugin', 'uninstall', 'codex', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const actions = JSON.parse(result.stdout).uninstalled[0].files.map((file) => file.action);
  assert.equal(actions[0], 'skip');
  assert.equal(await readFile(filePath, 'utf8'), '{"custom":true}\n');
});

test('plugin uninstall dry-run reports removal without deleting', async () => {
  const root = await workspace();
  assert.equal(cli('plugin', 'install', 'opencode', '--workspace', root, '--json').status, 0);
  const filePath = path.join(root, '.opencode', 'plugins', 'agents-crew.js');
  const result = cli('plugin', 'uninstall', 'opencode', '--workspace', root, '--dry-run', '--json');
  assert.equal(result.status, 0, result.stderr);
  const actions = JSON.parse(result.stdout).uninstalled[0].files.map((file) => file.action);
  assert.ok(actions.includes('remove'));
  assert.equal(existsSync(filePath), true);
});

test('plugin doctor warns before install', async () => {
  const root = await workspace();
  const result = cli('plugin', 'doctor', 'github-copilot', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const statuses = JSON.parse(result.stdout).doctor[0].checks.map((check) => check.status);
  assert.ok(statuses.includes('warn'));
});

test('plugin doctor passes generated files after install', async () => {
  const root = await workspace();
  assert.equal(cli('init', '--workspace', root, '--json').status, 0);
  assert.equal(cli('plugin', 'install', 'github-copilot', '--workspace', root, '--json').status, 0);
  const result = cli('plugin', 'doctor', 'github-copilot', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const statuses = JSON.parse(result.stdout).doctor[0].checks.map((check) => check.status);
  assert.equal(statuses.every((status) => status === 'pass'), true);
});

test('plugin doctor fails missing workspace', async () => {
  const root = path.join(await workspace(), 'missing');
  const result = cli('plugin', 'doctor', 'codex', '--workspace', root, '--json');
  assert.equal(result.status, 0, result.stderr);
  const workspaceCheck = JSON.parse(result.stdout).doctor[0].checks.find((check) => check.name === 'workspace');
  assert.equal(workspaceCheck.status, 'fail');
});

test('plugin rejects unknown host and action', () => {
  assert.notEqual(cli('plugin', 'install', 'unknown', '--json').status, 0);
  assert.notEqual(cli('plugin', 'unknown', '--json').status, 0);
});
