import path from 'node:path';
import type { CrewHostPlugin, PluginFilePlan, PluginHost, PluginInstallTarget, PluginManifest } from './plugin-contract';
import { createPluginManifest, renderCommandMarkdown, renderManifestJson } from './plugin-manifest';

interface HostConfig {
  host: PluginHost;
  displayName: string;
  summary: string;
  directory: string;
  notes: string[];
  hook?: { event: string; command: string; description: string };
}

const MARKER = 'generated by agents-crew plugin installer';

const HOSTS: HostConfig[] = [
  {
    host: 'antigravity',
    displayName: 'Antigravity',
    summary: 'Workspace hook and command manifest for Antigravity.',
    directory: '.agents/hooks',
    hook: {
      event: 'model_stop',
      command: 'agents-crew hook --adapter antigravity --json',
      description: 'Run review when Antigravity reports model_stop and the task is ready.',
    },
    notes: ['Wire the hook command into Antigravity workspace hooks.', 'Generated files never contain credentials.'],
  },
  {
    host: 'codex',
    displayName: 'Codex',
    summary: 'Command and Stop hook manifest for Codex CLI/task workflows.',
    directory: '.codex/agents-crew',
    hook: {
      event: 'Stop',
      command: 'agents-crew hook --adapter codex --json',
      description: 'Run review after a Codex turn stops and the task is ready.',
    },
    notes: ['Codex project hooks load from trusted `.codex/` layers.', 'Codex review execution still uses the existing read-only Codex adapter.'],
  },
  {
    host: 'claude-code',
    displayName: 'Claude Code',
    summary: 'Plugin directory with Stop hook and command manifest for Claude Code.',
    directory: '.claude/commands/agents-crew',
    hook: {
      event: 'Stop',
      command: 'agents-crew hook --adapter claude-code --json',
      description: 'Run review after Claude Code finishes a turn and the task is ready.',
    },
    notes: ['Claude Code plugin hooks live under a plugin `hooks/hooks.json` file.', 'Do not put API keys in generated command files.'],
  },
  {
    host: 'opencode',
    displayName: 'OpenCode',
    summary: 'Workspace plugin and command manifest for OpenCode.',
    directory: '.opencode/agents-crew',
    hook: {
      event: 'session.idle',
      command: 'agents-crew hook --adapter opencode --json',
      description: 'Run review when OpenCode emits session.idle and the task is ready.',
    },
    notes: ['OpenCode project plugins load from `.opencode/plugins/`.', 'Use OpenCode permission rules to approve automation as needed.'],
  },
  {
    host: 'github-copilot',
    displayName: 'GitHub Copilot',
    summary: 'Repository hook and plugin manifest for GitHub Copilot CLI.',
    directory: '.vscode/agents-crew-copilot',
    hook: {
      event: 'agentStop',
      command: 'agents-crew hook --adapter github-copilot --json',
      description: 'Run review when Copilot CLI agent execution stops and the task is ready.',
    },
    notes: ['Copilot repository hooks live in `.github/hooks/` with version 1.', 'Include both bash and powershell hook commands for cross-platform use.'],
  },
];

function createHostPlugin(config: HostConfig): CrewHostPlugin {
  return {
    host: config.host,
    displayName: config.displayName,
    summary: config.summary,
    manifest(): PluginManifest {
      return createPluginManifest(config.host, config.hook ? [config.hook] : [], config.notes);
    },
    files(target: PluginInstallTarget) {
      const manifest = this.manifest();
      const dir = path.join(target.workspace, config.directory);
      const common = [
        { path: path.join(dir, 'manifest.json'), content: renderManifestJson(manifest) },
        { path: path.join(dir, 'COMMANDS.md'), content: renderCommandMarkdown(manifest) },
      ];
      return [...common, ...hostSpecificFiles(config.host, target.workspace, manifest)];
    },
  };
}

function hostSpecificFiles(host: PluginHost, workspace: string, manifest: PluginManifest): PluginFilePlan[] {
  if (host === 'antigravity') return antigravityFiles(workspace);
  if (host === 'codex') return codexFiles(workspace);
  if (host === 'claude-code') return claudeFiles(workspace);
  if (host === 'opencode') return opencodeFiles(workspace);
  return copilotFiles(workspace, manifest);
}

function antigravityFiles(workspace: string): PluginFilePlan[] {
  return [{
    path: path.join(workspace, '.agents', 'hooks.json'),
    content: `${JSON.stringify({ generatedBy: MARKER, hooks: { model_stop: 'agents-crew hook --adapter antigravity --json' } }, null, 2)}\n`,
  }];
}

function codexFiles(workspace: string): PluginFilePlan[] {
  return [{
    path: path.join(workspace, '.codex', 'hooks.json'),
    content: `${JSON.stringify({ generatedBy: MARKER, hooks: { Stop: [{ hooks: [{ type: 'command', command: 'agents-crew hook --adapter codex --json', timeout: 300, statusMessage: 'Running agents-crew review' }] }] } }, null, 2)}\n`,
  }];
}

function claudeFiles(workspace: string): PluginFilePlan[] {
  const root = path.join(workspace, '.claude', 'plugins', 'agents-crew');
  return [
    {
      path: path.join(root, '.claude-plugin', 'plugin.json'),
      content: `${JSON.stringify({ name: 'agents-crew', description: 'Typed review-loop hooks for agents-crew.', version: '0.0.2', generatedBy: MARKER }, null, 2)}\n`,
    },
    {
      path: path.join(root, 'hooks', 'hooks.json'),
      content: `${JSON.stringify({ description: MARKER, hooks: { Stop: [{ hooks: [{ type: 'command', command: 'agents-crew hook --adapter claude-code --json', timeout: 300, statusMessage: 'Running agents-crew review' }] }] } }, null, 2)}\n`,
    },
  ];
}

function opencodeFiles(workspace: string): PluginFilePlan[] {
  return [{
    path: path.join(workspace, '.opencode', 'plugins', 'agents-crew.js'),
    content: [
      `// ${MARKER}`,
      'export const AgentsCrewPlugin = async ({ $ }) => ({',
      '  event: async ({ event }) => {',
      '    if (event.type === "session.idle") {',
      '      await $`echo "{}" | agents-crew hook --adapter opencode --json`',
      '    }',
      '  },',
      '})',
      '',
    ].join('\n'),
  }];
}

function copilotFiles(workspace: string, manifest: PluginManifest): PluginFilePlan[] {
  return [
    {
      path: path.join(workspace, '.github', 'hooks', 'agents-crew.json'),
      content: `${JSON.stringify({ version: 1, generatedBy: MARKER, hooks: { agentStop: [{ type: 'command', bash: 'agents-crew hook --adapter github-copilot --json', powershell: 'agents-crew hook --adapter github-copilot --json', cwd: '.', timeoutSec: 300 }] } }, null, 2)}\n`,
    },
    {
      path: path.join(workspace, '.github', 'copilot', 'agents-crew-plugin', 'plugin.json'),
      content: `${JSON.stringify({ name: 'agents-crew', description: 'Review-loop commands and hooks for agents-crew.', version: '0.0.2', hooks: '../../hooks/agents-crew.json', generatedBy: MARKER, keywords: manifest.commands.map((command) => command.name) }, null, 2)}\n`,
    },
  ];
}

export const PLUGIN_HOSTS: PluginHost[] = HOSTS.map((host) => host.host);
const plugins = new Map<PluginHost, CrewHostPlugin>(HOSTS.map((host) => [host.host, createHostPlugin(host)]));

export function getPlugin(host: PluginHost): CrewHostPlugin {
  const plugin = plugins.get(host);
  if (!plugin) throw new Error(`Unknown plugin host: ${host}`);
  return plugin;
}

export function getPlugins(): CrewHostPlugin[] {
  return PLUGIN_HOSTS.map((host) => getPlugin(host));
}
