import type { PluginCommandSpec, PluginHookSpec, PluginHost, PluginManifest } from './plugin-contract';

const BASE_COMMANDS: PluginCommandSpec[] = [
  { name: 'crew.setup', command: 'agents-crew setup --prepare --json', description: 'Create and prepare an agents-crew task.' },
  { name: 'crew.next', command: 'agents-crew next --json', description: 'Show the next participant to run.' },
  { name: 'crew.status', command: 'agents-crew status --json', description: 'Show task and automation state.' },
  { name: 'crew.review', command: 'agents-crew run --participant <reviewer-id> --json', description: 'Run a prepared reviewer participant.' },
];

export function createPluginManifest(host: PluginHost, hooks: PluginHookSpec[], notes: string[]): PluginManifest {
  return { name: 'agents-crew', host, generatedBy: 'generated by agents-crew plugin installer', commands: BASE_COMMANDS, hooks, notes };
}

export function renderManifestJson(manifest: PluginManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export function renderCommandMarkdown(manifest: PluginManifest): string {
  const lines = [
    '<!-- generated by agents-crew plugin installer; safe to regenerate -->',
    `# Agents Crew for ${manifest.host}`,
    '',
    'Use these commands from the host to coordinate `.agents-crew/` state.',
    '',
    '## Commands',
  ];
  for (const command of manifest.commands) {
    lines.push('', `- \`${command.name}\` - ${command.description}`, '', '```bash', command.command, '```');
  }
  if (manifest.hooks.length > 0) {
    lines.push('', '## Hooks');
    for (const hook of manifest.hooks) {
      lines.push('', `- \`${hook.event}\` - ${hook.description}`, '', '```bash', hook.command, '```');
    }
  }
  lines.push('', '## Notes');
  for (const note of manifest.notes) lines.push(`- ${note}`);
  lines.push('');
  return lines.join('\n');
}
