import fs from 'node:fs';
import path from 'node:path';
import { atomicWrite } from '../cli-utils';
import { PLUGIN_HOSTS, getPlugin, getPlugins } from './hosts';
import type { PluginDoctorCheck, PluginFilePlan, PluginFileResult, PluginHost, PluginInstallTarget, PluginTarget } from './plugin-contract';

const GENERATED_MARKER = 'generated by agents-crew plugin installer';

export interface PluginOptions extends PluginInstallTarget {
  target: PluginTarget;
}

export function resolvePluginHosts(target: PluginTarget): PluginHost[] {
  if (target === 'all') return [...PLUGIN_HOSTS];
  if (!PLUGIN_HOSTS.includes(target)) throw new Error(`Unknown plugin host: ${target}`);
  return [target];
}

export function listPlugins() {
  return getPlugins().map((plugin) => ({ host: plugin.host, displayName: plugin.displayName, summary: plugin.summary }));
}

export function installPlugins(options: PluginOptions) {
  return resolvePluginHosts(options.target).map((host) => ({
    host,
    files: installFiles(getPlugin(host).files(options), options),
    dryRun: options.dryRun,
  }));
}

export function uninstallPlugins(options: PluginOptions) {
  return resolvePluginHosts(options.target).map((host) => ({
    host,
    files: uninstallFiles(getPlugin(host).files(options), options.dryRun),
    dryRun: options.dryRun,
  }));
}

export function doctorPlugins(options: PluginOptions) {
  return resolvePluginHosts(options.target).map((host) => ({
    host,
    checks: doctorFiles(getPlugin(host).files(options), options.workspace),
  }));
}

function installFiles(files: PluginFilePlan[], options: PluginInstallTarget): PluginFileResult[] {
  return files.map((file) => {
    const exists = fs.existsSync(file.path);
    if (exists && !options.force) return { path: file.path, action: 'skip' };
    if (!options.dryRun) atomicWrite(file.path, file.content);
    return { path: file.path, action: exists ? 'overwrite' : 'create' };
  });
}

function uninstallFiles(files: PluginFilePlan[], dryRun: boolean): PluginFileResult[] {
  return files.map((file) => {
    if (!fs.existsSync(file.path)) return { path: file.path, action: 'missing' };
    const content = fs.readFileSync(file.path, 'utf8');
    if (!content.includes(GENERATED_MARKER)) return { path: file.path, action: 'skip' };
    if (!dryRun) fs.rmSync(file.path, { force: true });
    return { path: file.path, action: 'remove' };
  });
}

function doctorFiles(files: PluginFilePlan[], workspace: string): PluginDoctorCheck[] {
  const checks: PluginDoctorCheck[] = [];
  checks.push({
    name: 'workspace',
    status: fs.existsSync(workspace) ? 'pass' : 'fail',
    message: fs.existsSync(workspace) ? `Workspace exists: ${workspace}` : `Workspace missing: ${workspace}`,
  });
  checks.push({
    name: 'state-directory',
    status: fs.existsSync(path.join(workspace, '.agents-crew')) ? 'pass' : 'warn',
    message: fs.existsSync(path.join(workspace, '.agents-crew')) ? '.agents-crew exists' : 'Run agents-crew init or setup before automation.',
  });
  for (const file of files) {
    const exists = fs.existsSync(file.path);
    checks.push({
      name: path.relative(workspace, file.path).replace(/\\/g, '/'),
      status: exists ? 'pass' : 'warn',
      message: exists ? 'Generated file exists.' : 'Generated file missing; run plugin install.',
    });
  }
  return checks;
}
